spring.application.name=SIMS


server.port = 8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sims_db
spring.datasource.username=postgres
spring.datasource.password=pariharPost123@
# spring.datasource.driver-class-name=org.postgresql.Driver